### ISSUE TITLE
Date Bug in Thread View

### ISSUE THREAD

**Issue by DB-CH** [flarum-lang/french#68] opened 2024-11-01 17:25 UTC
see attached screenshot.

it should not say AMAMAM, it should be 2024 ;-) 

English and German are displayed correct.
![Bildschirmfoto_1-11-2024_182333_forum vsh-suisse ch](https://github.com/user-attachments/assets/5f6c05c8-5185-4b7c-bb02-51ce70e5bb0b)

**Comment by qiaeru** [comment] 2024-11-02 12:45
Mmmh I can't reproduce the issue on my side.

**Comment by qiaeru** [comment] 2024-11-13 19:41
Also reported here: https://discuss.flarum.org/d/615-french-language-pack/372

**Comment by qiaeru** [comment] 2024-11-17 09:49
This should be resolved with the new release: https://github.com/flarum-lang/french/pull/69#pullrequestreview-2440911258

**Closed by qiaeru** 2024-11-17 09:49 UTC
